services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: auth-db

    ports:
      - 27017:27017

  auth-server:
    image: ericmiddelhove/erics-auth-server
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_URI="mongodb://mongo:27017"
      - RUST_BACKTRACE=0
      - VERIFY_SECRET="aölsdfjadgöflhdfhg0ew94g8ur3q980374256-sfoüasefg uiushfaiofaöruh5§$%/()=ndkjalbdsferiuzelqugQFW8NZß9Z8N9WOXGEQWPÜ,,ÜUhtervnteruicnwliet5hectlwhneritcbcoeirtgwleuihtnxiwxnetx712nrtx40238ß3tz02394t8zq#weüfp32p894czp8 7nt<9c8pz7290c45zp2xu3hrpmyox24phnv2t19x8634tr10287rtßnmßqxwe9z6tbcrß80tgQ8W9N475Ü 9MU8ß^x0´tv1x0ru29x3407tcr378t9c23t"
